## 
## # Targets for managing the REPRO-local Blazegraph instance

clean:                 ## Delete the Blazegraph logs.
	rm -f *.log
	
drop:                   ## Delete the Blazegraph storage file.
	rm -f blazegraph.diskrw

## purge-blazegraph:       Delete all artifacts associated with Blazegraph instance.
purge: clean drop

