#!/bin/bash

# work in builders subdirectory
cd `dirname $0`/builders

# install wget so that missing builder scripts can be downloaded
apt-get -y update
apt-get -y install wget

# if [[ ! -f initialize-repro ]] ; then
#     echo "MISSING"
# fi

function repro.setenv {
    name=$1
    value=$2
    export ${name}=${value}
    echo "export ${name}=${value}" >> ${DOT_ENV}
}

source 010_install_required_packages
source 020_create_repro_user
source 030_install_builders
source 040_install_optional_packages
source 050_initialize_environment

