#!/bin/bash

# work in REPRO builder directory
REPRO_BUILDER_DIR=`dirname $0`
cd ${REPRO_BUILDER_DIR}

# install wget so that missing builder scripts can be downloaded
apt-get -y update
apt-get -y install wget

# if [[ ! -f initialize-repro ]] ; then
#     echo "MISSING"
# fi

source 010_install_required_packages
source 020_create_repro_user
source 030_install_builders
source 040_install_optional_packages
source 050_initialize_environment

