#!/bin/bash

# work in repro-builder cache directory
REPRO_BUILDER_DIR=`readlink -f $(dirname $0)`
cd ${REPRO_BUILDER_DIR}/cache

# install wget so that missing builder scripts can be downloaded
apt-get -y update
apt-get -y install wget

# if [[ ! -f initialize-repro ]] ; then
#     echo "MISSING"
# fi

source 010_install_required_packages
source 020_create_repro_user
source 030_initialize_environment
source 040_install_builders
source 050_install_optional_packages
source 060_configure_startup

