#!/bin/bash

# work in repro-builder cache directory
REPRO_BUILDER_DIR=`readlink -f $(dirname $0)`
cd ${REPRO_BUILDER_DIR}/cache


# install wget so that missing builder scripts can be downloaded
apt-get -y update
apt-get -y install wget

# if [[ ! -f initialize-repro ]] ; then
#     echo "MISSING"
# fi

for filename in [0-9]*; do
    echo -e "\nSTARTING  ${filename}\n"
    source $filename
    echo -e "\nFINISHED ${filename}\n"
done
